export const TICKET_AGGREGATOR_TOKEN = Symbol('TICKET_AGGREGATOR_TOKEN');
export const TICKET_SERVICE_TOKEN = Symbol('TICKET_SERVICE_TOKEN');
export const TICKET_NUMBER_SERVICE_TOKEN = Symbol(
  'TICKET_NUMBER_SERVICE_TOKEN'
);
export const COMMENT_SERVICE_TOKEN = Symbol('COMMENT_SERVICE_TOKEN');
